#!/bin/bash
# Update the system
yum update -y

# Install Apache (httpd) and PHP
yum install -y httpd php

# Start Apache service and enable it to run on boot
systemctl start httpd
systemctl enable httpd

# Add a simple PHP file to test
echo "<?php phpinfo(); ?>" > /var/www/html/index.php


# Confirm Apache is running
systemctl status httpd
